/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 from proto/canairio_payload.proto */

#include <pb.h>
#include "canairio_payload.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CanAirIOPayload, CanAirIOPayload, AUTO)
