/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 from proto/canairio_payload.proto */

#ifndef PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED
#define PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CanAirIOPayload {
    uint32_t pm1;    /* PM1.0  ug/m3 x10 */
    uint32_t pm25;   /* PM2.5  ug/m3 x10 */
    uint32_t pm10;   /* PM10   ug/m3 x10 */
    uint32_t co2;    /* CO2    ppm   x10 */
    uint32_t co2h;   /* CO2 sensor humidity  % x10 */
    int32_t  co2t;   /* CO2 sensor temp      C x10 (ZigZag encoded) */
    int32_t  temp;   /* Main temperature     C x10 (ZigZag encoded) */
    uint32_t humi;   /* Main humidity        % x10 */
    uint32_t press;  /* Barometric pressure  hPa x10 */
    uint32_t gas;    /* Gas resistance       Ohm x10 */
    uint32_t nh3;    /* Ammonia              ppm x10 */
    uint32_t co;     /* Carbon monoxide      ppm x10 */
    int32_t  alt;    /* Altitude             m (ZigZag encoded) */
    uint32_t batt;   /* Battery charge       % x10 */
    uint32_t volt;   /* Battery voltage      mV */
    uint32_t heap;   /* Free heap            bytes/100 */
} CanAirIOPayload;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CanAirIOPayload_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define CanAirIOPayload_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags */
#define CanAirIOPayload_pm1_tag    1
#define CanAirIOPayload_pm25_tag   2
#define CanAirIOPayload_pm10_tag   3
#define CanAirIOPayload_co2_tag    4
#define CanAirIOPayload_co2h_tag   5
#define CanAirIOPayload_co2t_tag   6
#define CanAirIOPayload_temp_tag   7
#define CanAirIOPayload_humi_tag   8
#define CanAirIOPayload_press_tag  9
#define CanAirIOPayload_gas_tag    10
#define CanAirIOPayload_nh3_tag    11
#define CanAirIOPayload_co_tag     12
#define CanAirIOPayload_alt_tag    13
#define CanAirIOPayload_batt_tag   14
#define CanAirIOPayload_volt_tag   15
#define CanAirIOPayload_heap_tag   16

/* Struct field encoding specification for nanopb */
#define CanAirIOPayload_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, pm1,    1) \
X(a, STATIC, SINGULAR, UINT32, pm25,   2) \
X(a, STATIC, SINGULAR, UINT32, pm10,   3) \
X(a, STATIC, SINGULAR, UINT32, co2,    4) \
X(a, STATIC, SINGULAR, UINT32, co2h,   5) \
X(a, STATIC, SINGULAR, SINT32, co2t,   6) \
X(a, STATIC, SINGULAR, SINT32, temp,   7) \
X(a, STATIC, SINGULAR, UINT32, humi,   8) \
X(a, STATIC, SINGULAR, UINT32, press,  9) \
X(a, STATIC, SINGULAR, UINT32, gas,   10) \
X(a, STATIC, SINGULAR, UINT32, nh3,   11) \
X(a, STATIC, SINGULAR, UINT32, co,    12) \
X(a, STATIC, SINGULAR, SINT32, alt,   13) \
X(a, STATIC, SINGULAR, UINT32, batt,  14) \
X(a, STATIC, SINGULAR, UINT32, volt,  15) \
X(a, STATIC, SINGULAR, UINT32, heap,  16)

#define CanAirIOPayload_CALLBACK NULL
#define CanAirIOPayload_DEFAULT  NULL

extern const pb_msgdesc_t CanAirIOPayload_msg;
#define CanAirIOPayload_fields &CanAirIOPayload_msg

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED */
