/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 from proto/canairio_payload.proto */

#ifndef PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED
#define PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _CanAirIOPayload {
    uint32_t pm1;       /* PM1.0  ug/m3 x10 */
    uint32_t pm25;      /* PM2.5  ug/m3 x10 */
    uint32_t pm4;       /* PM4.0  ug/m3 x10 */
    uint32_t pm10;      /* PM10   ug/m3 x10 */
    uint32_t co2;       /* CO2    ppm x10 */
    uint32_t co2h;      /* CO2 sensor humidity  % x10 */
    int32_t  co2t;      /* CO2 sensor temp      C x10 (ZigZag) */
    int32_t  temp;      /* Temperature          C x10 (ZigZag) */
    uint32_t humi;      /* Humidity             % x10 */
    uint32_t press;     /* Barometric pressure  hPa x10 */
    int32_t  alt;       /* Altitude             m (ZigZag) */
    uint32_t gas;       /* Gas resistance (BME680)  kOhm x100 */
    uint32_t nh3;       /* Ammonia              ppm x10 */
    uint32_t co;        /* Carbon monoxide      ppm x10 */
    uint32_t no2;       /* Nitrogen dioxide     ppm x10 */
    uint32_t o3;        /* Ozone                ppm x10 */
    uint32_t voc;       /* VOC index generic    0-500 x10 */
    uint32_t nox;       /* NOX index generic    0-500 x10 */
    uint32_t voci;      /* VOC index SGP41      0-500 x10 */
    uint32_t noxi;      /* NOX index SGP41      0-500 x10 */
    uint32_t cpm;       /* Counts per minute (Geiger) */
    uint32_t rad;       /* Radiation dose       uSv/h x100 */
    uint32_t noise;     /* Instantaneous noise  dB x10 */
    uint32_t noiseAvg;  /* Average noise        dB x10 */
    uint32_t noisePeak; /* Peak noise           dB x10 */
    uint32_t noiseMin;  /* Minimum noise        dB x10 */
    uint32_t noiseLegal;     /* Legal avg noise   dB x10 */
    uint32_t noiseLegalMax;  /* Legal max noise   dB x10 */
    uint32_t noiseLd;   /* Index Ld (day)       dB x10 */
    uint32_t noiseLe;   /* Index Le (evening)   dB x10 */
    uint32_t noiseLn;   /* Index Ln (night)     dB x10 */
    uint32_t noiseLden; /* Index Lden (day-eve-night) dB x10 */
    uint32_t batt;      /* Battery charge       % x10 */
    uint32_t volt;      /* Battery voltage      mV */
    uint32_t heap;      /* Free heap            bytes/100 */
} CanAirIOPayload;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CanAirIOPayload_init_default  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define CanAirIOPayload_init_zero     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags */
#define CanAirIOPayload_pm1_tag       1
#define CanAirIOPayload_pm25_tag      2
#define CanAirIOPayload_pm4_tag       3
#define CanAirIOPayload_pm10_tag      4
#define CanAirIOPayload_co2_tag       5
#define CanAirIOPayload_co2h_tag      6
#define CanAirIOPayload_co2t_tag      7
#define CanAirIOPayload_temp_tag      8
#define CanAirIOPayload_humi_tag      9
#define CanAirIOPayload_press_tag     10
#define CanAirIOPayload_alt_tag       11
#define CanAirIOPayload_gas_tag       12
#define CanAirIOPayload_nh3_tag       13
#define CanAirIOPayload_co_tag        14
#define CanAirIOPayload_no2_tag       15
#define CanAirIOPayload_o3_tag        16
#define CanAirIOPayload_voc_tag       17
#define CanAirIOPayload_nox_tag       18
#define CanAirIOPayload_voci_tag      19
#define CanAirIOPayload_noxi_tag      20
#define CanAirIOPayload_cpm_tag       21
#define CanAirIOPayload_rad_tag       22
#define CanAirIOPayload_noise_tag     23
#define CanAirIOPayload_noiseAvg_tag  24
#define CanAirIOPayload_noisePeak_tag 25
#define CanAirIOPayload_noiseMin_tag  26
#define CanAirIOPayload_noiseLegal_tag    27
#define CanAirIOPayload_noiseLegalMax_tag 28
#define CanAirIOPayload_noiseLd_tag   29
#define CanAirIOPayload_noiseLe_tag   30
#define CanAirIOPayload_noiseLn_tag   31
#define CanAirIOPayload_noiseLden_tag 32
#define CanAirIOPayload_batt_tag      33
#define CanAirIOPayload_volt_tag      34
#define CanAirIOPayload_heap_tag      35

/* Struct field encoding specification for nanopb */
#define CanAirIOPayload_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, pm1,     1) \
X(a, STATIC, SINGULAR, UINT32, pm25,    2) \
X(a, STATIC, SINGULAR, UINT32, pm4,     3) \
X(a, STATIC, SINGULAR, UINT32, pm10,    4) \
X(a, STATIC, SINGULAR, UINT32, co2,     5) \
X(a, STATIC, SINGULAR, UINT32, co2h,    6) \
X(a, STATIC, SINGULAR, SINT32, co2t,    7) \
X(a, STATIC, SINGULAR, SINT32, temp,    8) \
X(a, STATIC, SINGULAR, UINT32, humi,    9) \
X(a, STATIC, SINGULAR, UINT32, press,  10) \
X(a, STATIC, SINGULAR, SINT32, alt,    11) \
X(a, STATIC, SINGULAR, UINT32, gas,    12) \
X(a, STATIC, SINGULAR, UINT32, nh3,    13) \
X(a, STATIC, SINGULAR, UINT32, co,     14) \
X(a, STATIC, SINGULAR, UINT32, no2,    15) \
X(a, STATIC, SINGULAR, UINT32, o3,     16) \
X(a, STATIC, SINGULAR, UINT32, voc,    17) \
X(a, STATIC, SINGULAR, UINT32, nox,    18) \
X(a, STATIC, SINGULAR, UINT32, voci,   19) \
X(a, STATIC, SINGULAR, UINT32, noxi,   20) \
X(a, STATIC, SINGULAR, UINT32, cpm,    21) \
X(a, STATIC, SINGULAR, UINT32, rad,    22) \
X(a, STATIC, SINGULAR, UINT32, noise,  23) \
X(a, STATIC, SINGULAR, UINT32, noiseAvg,     24) \
X(a, STATIC, SINGULAR, UINT32, noisePeak,    25) \
X(a, STATIC, SINGULAR, UINT32, noiseMin,     26) \
X(a, STATIC, SINGULAR, UINT32, noiseLegal,   27) \
X(a, STATIC, SINGULAR, UINT32, noiseLegalMax, 28) \
X(a, STATIC, SINGULAR, UINT32, noiseLd,  29) \
X(a, STATIC, SINGULAR, UINT32, noiseLe,  30) \
X(a, STATIC, SINGULAR, UINT32, noiseLn,  31) \
X(a, STATIC, SINGULAR, UINT32, noiseLden, 32) \
X(a, STATIC, SINGULAR, UINT32, batt,   33) \
X(a, STATIC, SINGULAR, UINT32, volt,   34) \
X(a, STATIC, SINGULAR, UINT32, heap,   35)

#define CanAirIOPayload_CALLBACK NULL
#define CanAirIOPayload_DEFAULT  NULL

extern const pb_msgdesc_t CanAirIOPayload_msg;
#define CanAirIOPayload_fields &CanAirIOPayload_msg

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* PB_CANAIRIO_PAYLOAD_PB_H_INCLUDED */
